"""Prose-check: README numbers must exist in a quotable source.

The README's findings section is the project's public face; its numbers
drifted once already (30.7% early quoted while the frozen data said 30.0%,
then the live mid-window API said 33.0% — three numbers for one truth).
This test fails CI when a headline number in the README's findings or
model-results sections is not present in (or consistent with) a quotable
source: the immutable findings snapshots, the pinned solver receipts, the
window-close weekly rollup, or the realized-waits snapshot.

Rules of the check (kept deliberately conservative to avoid false
positives that would teach people to ignore it):

* Only numbers in the two findings/model sections of the README are
  checked — the rest of the page (install commands, port numbers, panel
  descriptions) is not data.
* Percentages with sample sizes (e.g. "30.0% ... (n = 622,183)") are
  checked against the source corpora for BOTH the rate and the n.
* A number passes if it appears verbatim in any quotable source file, OR
  is derived by the whitelisted derivations below (weighted rollup mean,
  ghost ratio). Derivations must stay whitelisted — a derivation that
  can't be explained in one line doesn't belong in the README.
* Ranges ("38–41 min", "51–64%") pass when both endpoints are quotable.

Sources considered quotable:
* docs/findings/*.md (immutable snapshots — the DRAFT skeleton's TODOs are
  never numbers, so drafts can't leak quotes)
* docs/runs/*.md (solver receipts, verdicts — pinned artifacts)
* docs/sources/gtfs_archive/MANIFEST.md (feed vintages)
* backend/app/data/weekly_rollup.csv (window-close deduped, machine-read)
* backend/app/data/realized_waits.csv (pinned realized-waits snapshot)

NOT quotable: the live API, live CSVs mid-window, memory, vibes.

Scope added 2026-09-04 — two more public surfaces:

* ``docs/councillor-email-draft.md``: the email mixes two number classes.
  *Document claims* (58.4M boardings, 240.9M journeys, 57,000 hours, the
  boardings/journey pair) are stable and enforced against the sources
  archive below. *Collector-window numbers* (crowding %, n= counts, ghost
  rates) are regenerated by ``scripts/build_councillor_email.py`` after
  every window — pinning them here would false-fail each rebuild, so they
  are exempt by design and guarded instead by the committed generator plus
  the committed data artifacts it reads. The boundary is the Key-numbers
  table's own source column: rows citing ``.csv``/``.json`` artifacts are
  collector class; everything else is document class.
* ``GET /api/peers``: every figure the endpoint serves is either read from
  committed peer CSVs, a module constant, or MiWay's published annual
  series — each must match its quotable source. The MiWay 2019 slot must
  stay None (never published) and the journey-stats contrast must keep its
  identifiability wording.
"""

from __future__ import annotations

import re
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
README = _ROOT / "README.md"

# Findings + model sections: everything between these headings is checked.
_SECTION_START = "## Findings presented to the City"
_SECTION_END = "## Quick start"

_QUOTABLE_GLOBS = [
    _ROOT / "docs" / "findings" / "*.md",
    _ROOT / "docs" / "runs" / "*.md",
    _ROOT / "docs" / "sources" / "gtfs_archive" / "MANIFEST.md",
]


def _checked_text() -> str:
    text = README.read_text(encoding="utf-8")
    start = text.index(_SECTION_START)
    end = text.index(_SECTION_END)
    return text[start:end]


def _corpus() -> str:
    parts = []
    for pattern in _QUOTABLE_GLOBS:
        for p in sorted(_ROOT.glob(str(pattern.relative_to(_ROOT)))):
            parts.append(p.read_text(encoding="utf-8"))
    return "\n".join(parts)


def _rollup_derived_numbers() -> set[str]:
    """Numbers derivable from the window-close rollup, formatted as the
    README formats them. One whitelisted derivation per line."""
    import csv

    path = _ROOT / "backend" / "app" / "data" / "weekly_rollup.csv"
    if not path.exists():
        return set()
    with path.open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        return set()
    out: set[str] = set()
    n_total = sum(int(float(r["n_recorded"] or 0)) for r in rows)
    if n_total:
        early = (
            sum(
                float(r["pct_early_gt2"] or 0) * int(float(r["n_recorded"] or 0))
                for r in rows
            )
            / n_total
        )
        out.add(f"{early:.1f}%")
        out.add(f"n = {n_total:,}")
    ghosts = sum(int(float(r["ghost_trips"] or 0)) for r in rows)
    verifiable = sum(int(float(r["verifiable_trips"] or 0)) for r in rows)
    if ghosts:
        out.add(f"1 in {round(verifiable / ghosts)}")
    return out


def _realized_waits_derived() -> set[str]:
    """Numbers derivable from the realized-waits snapshot (p90 band,
    missed-share band, pairing count). Whitelisted derivations only."""
    import csv

    path = _ROOT / "backend" / "app" / "data" / "realized_waits.csv"
    if not path.exists():
        return set()
    with path.open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    out: set[str] = set()
    band = [
        r
        for r in rows
        if 38 <= float(r["realized_p90_min"]) <= 41
        and 0.51 <= float(r["realized_missed_share"]) <= 0.66
    ]
    out.add(str(len(band)))  # pairing count in the quoted band
    if band:
        lo = round(min(float(r["realized_missed_share"]) for r in band) * 100)
        hi = round(max(float(r["realized_missed_share"]) for r in band) * 100)
        out.add(f"{lo}–{hi}%")
        out.add(f"{lo}-{hi}%")
    return out


def _extract_claims(text: str) -> list[tuple[str, str]]:
    """(number-as-written, context-line) pairs worth checking."""
    claims = []
    for line in text.splitlines():
        # Skip lines that are explicitly historical/presented labels.
        if "presented" in line.lower() or "v1:" in line:
            continue
        for m in re.finditer(
            r"\d[\d,]*(?:\.\d+)?(?:\s*[–-]\s*\d[\d,]*(?:\.\d+)?)?(?:\s*%)?", line
        ):
            tok = m.group(0).strip()
            # Filter obvious non-data: years, section numbers, small ints
            # with units like "12 routes" stay (they are data claims).
            claims.append((tok, line.strip()[:120]))
    return claims


def test_readme_findings_numbers_exist_in_quotable_sources():
    text = _checked_text()
    corpus = _corpus()
    derived = _rollup_derived_numbers() | _realized_waits_derived()

    # Numbers with units/words that are claims, not dates or headings.
    # A claim must contain a %, a decimal, a "1 in N", or be >= 3 digits —
    # anything else (route numbers, "277", "2x2") is too generic to police
    # mechanically and is covered by review.
    unexplained: list[str] = []
    for tok, line in _extract_claims(text):
        if not (
            "%" in tok
            or re.search(r"^\d[\d,]*\.\d+$", tok)
            or re.match(r"^1 in \d", tok)
            or re.fullmatch(r"\d{3,}[\d,]*", tok)
        ):
            continue
        # Both endpoints of a range must be findable; allow the range token.
        parts = re.split(r"\s*[–-]\s*", tok)
        for part in parts:
            part = part.strip().rstrip("%").replace(",", "")
            if not part or re.fullmatch(r"\d{4}", part):  # years/dates pass
                continue
            if part in corpus.replace(",", "") or tok in corpus:
                continue
            if any(part in d.replace(",", "") for d in derived):
                continue
            unexplained.append(f"{tok!r} <- line: {line!r}")

    assert not unexplained, (
        "README quotes numbers with no quotable source "
        "(docs/findings, docs/runs, MANIFEST, weekly rollup, realized waits). "
        "Either add the number to a snapshot/receipt, or fix the README:\n"
        + "\n".join(unexplained[:15])
    )


def test_check_catches_a_fabricated_number():
    """Guard the guard: inject a fake number and prove the check fails."""
    original = README.read_text(encoding="utf-8")
    # Sentinel must be distinctive: committed run CSVs carry float artifacts
    # like "...9999999999998", and the corpus test is a substring match — a
    # 999999999 sentinel accidentally appeared quotable after those runs
    # landed (2026-09-17), silently disarming this guard-the-guard test.
    # 999999991 does not occur in any quotable source.
    poisoned = original.replace(
        _SECTION_END,
        "999999991 unexplained\n\n" + _SECTION_END,
        1,
    )
    assert "999999991" in poisoned
    README.write_text(poisoned, encoding="utf-8")
    try:
        # Re-run the check logic inline (can't call pytest recursively).
        corpus = _corpus()
        derived = _rollup_derived_numbers() | _realized_waits_derived()
        checked = poisoned[
            poisoned.index(_SECTION_START) : poisoned.index(_SECTION_END)
        ]
        found = False
        for tok, _line in _extract_claims(checked):
            if re.fullmatch(r"\d{3,}[\d,]*", tok) and tok not in corpus:
                if not any(tok.replace(",", "") in d for d in derived):
                    found = True
                    break
        assert found, "the check did NOT catch a fabricated number"
    finally:
        README.write_text(original, encoding="utf-8")


def test_v2_draft_contains_no_quotable_numbers_yet():
    """The draft skeleton must be TODO-only — a draft that already carries
    numbers would let prose quote it as if frozen."""
    draft = _ROOT / "docs" / "findings" / "findings-v2-post-sept7-DRAFT.md"
    if not draft.exists():
        return  # renamed after the window closes; check no longer applies
    text = draft.read_text(encoding="utf-8")
    assert "STATUS: DRAFT SKELETON" in text
    # No frozen-style rate claims: no "XX.X%" outside v1-baseline lines
    # (v1 references are quotable — they point at the immutable v1 file).
    for line in text.splitlines():
        if (
            "v1:" in line
            or "v1 " in line
            or "30.0%" in line
            or "37%" in line
            or "README resync" in line  # quotes other quotable sources
        ):
            continue
        if re.search(r"\d\d\.\d%|\d\d%", line) and "TODO" not in line:
            raise AssertionError(
                f"draft carries an unfrozen rate claim: {line.strip()!r}"
            )


# ---------------------------------------------------------------------------
# Email prose-check (scope added 2026-09-04)
# ---------------------------------------------------------------------------

# 45353cf (2026-09-24 docs consolidation) archived the era doc to
# docs/archive/root/; this path was never updated (same class of miss as
# test_ridership_band_lyu's, fixed 2026-09-28). Prefer the live location,
# fall back to the pre-consolidation path for older checkouts.
_EMAIL = _ROOT / "docs" / "archive" / "root" / "councillor-email-draft.md"
if not _EMAIL.exists():
    _EMAIL = _ROOT / "docs" / "councillor-email-draft.md"

# The sources archive itself is quotable for document-class claims: any
# figure in an archived primary (or the README's documented derivations of
# them) may appear in the email. PDFs are pre-extracted to *_extracted.txt;
# the news release is archived as HTML.
_ARCHIVE_GLOBS = [
    "docs/sources/*_extracted.txt",
    "docs/sources/*.md",
    "docs/sources/*/README.md",
    "docs/sources/miway_57000_hours_news_release_2024.html",
    "docs/citation-review.md",
    "docs/data-share/CODEBOOK.md",
    "docs/capacity-calibration-findings.md",
]


def _archive_corpus() -> str:
    parts = []
    for rel in _ARCHIVE_GLOBS:
        for p in sorted(_ROOT.glob(rel)):
            try:
                parts.append(p.read_text(encoding="utf-8"))
            except OSError:
                continue
    return "\n".join(parts)


def _email_checked_lines() -> list[str]:
    """The narrative body only — stop at the audit appendix, which describes
    the numbers rather than quoting them (and which the generator owns)."""
    text = _EMAIL.read_text(encoding="utf-8")
    return text.split("## What's in this email")[0].splitlines()


def test_email_document_claims_trace_to_archived_sources():
    """Every stable document-class number in the email body must appear in
    the sources archive (or a whitelisted derivation of it).

    Collector-window numbers (percent-of-capacity, n= sample sizes, ghost
    counts, lateness rates) are exempt: they are regenerated per window by
    the committed generator from committed CSVs — see module docstring.
    """
    corpus = _archive_corpus().replace(",", "")
    # Whitelisted derivations: (pattern-in-email, explanation, expected forms
    # in corpus). One line each — an unexplained derivation doesn't belong.
    derived_whitelist = [
        # 2024 TransLink boardings/journeys pair, derivation documented in
        # docs/sources/README.md (open-data sums vs published journeys).
        (r"1\.6\d?", "boardings/journey 2024", ("1.67", "1.73")),
        (r"400\s*million", "system boardings 2024", ("401", "401.8")),
        # The 2019 baseline band, triangulated in docs/sources/README.md.
        (r"\b54M\b", "triangulated 2019 baseline", ("54", "54.1", "54.5")),
    ]

    unexplained: list[str] = []
    for line in _email_checked_lines():
        # Document-class check: million/billion/M-suffixed figures only.
        # Collector-window percentages (42% full, 27.3% early, ...) are
        # regenerated every rebuild by scripts/build_councillor_email.py
        # from the committed obs/occupancy CSVs — they are guarded by the
        # committed generator + committed data, NOT by the archive corpus,
        # which would false-fail every window refresh. (Fabricated
        # percentages in a hand-edited draft are caught by review; the
        # CI-enforced path is the generator, which is committed.)
        for m in re.finditer(
            r"\d[\d,]*(?:\.\d+)?\s*(?:million|billion|M\b)", line, re.I
        ):
            tok = m.group(0).strip()
            bare = tok.replace(",", "")
            num = re.match(r"\d[\d,]*(?:\.\d+)?", bare).group(0)
            if re.fullmatch(r"\d{4}", num):  # years pass
                continue
            if num in corpus or bare in corpus:
                continue
            if any(
                re.fullmatch(pat, tok.strip("%M ")) for pat, _, _ in derived_whitelist
            ):
                continue
            if any(
                exp in corpus for _, _, exps in derived_whitelist for exp in exps
            ) and any(re.fullmatch(pat, num) for pat, _, _ in derived_whitelist):
                continue
            unexplained.append(f"{tok!r} <- {line.strip()[:120]!r}")

    assert not unexplained, (
        "councillor email quotes document-class numbers with no archived "
        "source (docs/sources/*_extracted.txt, *.md, news release). Either "
        "archive the primary or fix the email:\n" + "\n".join(unexplained[:15])
    )


def test_email_catch_fabricated_document_claim():
    """Guard the guard: a fabricated document-class number must fail."""
    # Poison value chosen to be absent from the archive corpus (asserted
    # when this gate was written; re-check if the corpus grows onto it).
    # Poison IN MEMORY: writing the committed draft (even with a restore)
    # races under xdist — a parallel worker can read the poisoned file.
    original = _EMAIL.read_text(encoding="utf-8")
    poisoned = original.replace(
        "Happy to share the full dataset",
        "MiWay carried 97.4 million boardings in 2017. Happy to share the full dataset",
        1,
    )
    assert "97.4 million" in poisoned
    corpus = _archive_corpus().replace(",", "")
    caught = False
    for line in poisoned.split("## What's in this email")[0].splitlines():
        for m in re.finditer(r"\d[\d,]*(?:\.\d+)?\s*million", line, re.I):
            num = re.match(r"\d[\d,]*(?:\.\d+)?", m.group(0)).group(0)
            if num == "97.4" and num not in corpus:
                caught = True
    assert caught, "fabricated document claim was not caught"


# ---------------------------------------------------------------------------
# Peers payload prose-check (scope added 2026-09-04)
# ---------------------------------------------------------------------------


def _peers_payload() -> dict:
    import sys

    sys.path.insert(0, str(_ROOT / "backend"))
    from fastapi.testclient import TestClient

    from app.main import app

    return TestClient(app).get("/api/peers").json()


def test_peers_payload_numbers_match_committed_data():
    """Every figure /api/peers serves must match a committed artifact or an
    archived primary. MiWay's 2019 slot must stay None, and the journey-stats
    contrast must keep its identifiability wording."""
    data = _peers_payload()

    # TransLink card numbers must equal the committed demo CSV sums.
    import csv

    ridership = (
        _ROOT / "backend" / "app" / "data" / "peers" / "translink" / "ridership.csv"
    )
    if ridership.exists() and data.get("translink"):
        with ridership.open(encoding="utf-8") as f:
            rows = [r for r in csv.DictReader(f) if r.get("tspr_year") == "2024"]
        committed_total = sum(int(float(r["boardings"])) for r in rows)
        assert data["translink"]["total_boardings"] == committed_total

    # The boardings-per-journey figure must match the archived derivation.
    js = (data.get("translink") or {}).get("journey_stats") or {}
    readme = (_ROOT / "docs" / "sources" / "README.md").read_text(encoding="utf-8")
    if js.get("boardings_per_journey") is not None:
        assert f"{js['boardings_per_journey']:.2f}" in readme
        assert "1.73" in js.get("corroborating_pair", "")

    # MiWay annual series: every point must cite a source, 2019 stays None,
    # and published values must match the archived primary documents.
    series = {p["year"]: p for p in data["miway_annual_series"]}
    assert series[2019]["boardings_millions"] is None
    corpus = _archive_corpus().replace(",", "")
    for year, p in series.items():
        assert p["source"], f"{year} point has no source"
        val = p["boardings_millions"]
        if val is None:
            continue
        formatted = f"{val:.1f}" if val % 1 else str(int(val))
        assert formatted in corpus, (
            f"peers series {year}={val}M not found in archived sources"
        )

    # Journey-stats honesty: MiWay null with the derivability reason.
    mjs = (data.get("miway") or {}).get("journey_stats") or {}
    assert mjs.get("boardings_per_journey") is None
    assert "deriv" in mjs.get("source", "").lower()

    # FAO-anchored recovery index: every index value must be printed in the
    # archived derivation, and the FAO Ontario rows must match its table.
    idx = data.get("miway_recovery_index") or {}
    if idx:
        fao_readme = (
            (_ROOT / "docs" / "sources" / "fao-transit-2024" / "README.md")
            .read_text(encoding="utf-8")
            .replace(",", "")
        )
        for pt in idx["points"]:
            assert f"{pt['index_2019']:.1f}" in fao_readme.replace(",", ""), (
                f"recovery index {pt['year']}={pt['index_2019']} not in the "
                "FAO derivation"
            )
        ctx = data.get("ontario_context") or {}
        for row in ctx.get("rows", []):
            for year, val in row["trips_millions"].items():
                assert f"{val}" in fao_readme.replace(",", ""), (
                    f"ontario row {row['agency']} {year}={val} not in the FAO table"
                )
        # The as-published series keeps its honest 2019 hole alongside.
        ttc_readme = (
            (_ROOT / "docs" / "sources" / "ttc-surface-route-stats" / "README.md")
            .read_text(encoding="utf-8")
            .replace(",", "")
        )
        for pt in (data.get("ttc_surface_fall_index") or {}).get("points", []):
            assert f"{pt['index_2019']:.1f}" in ttc_readme.replace(",", ""), (
                f"ttc index {pt['year']}={pt['index_2019']} not in the Munro derivation"
            )
        # Service-supply rows: raw values and pct changes must be printed in
        # the supply derivation (or its quoted Munro/TSPR sources).
        supply_readme = (
            (_ROOT / "docs" / "sources" / "miway-service-supply" / "README.md")
            .read_text(encoding="utf-8")
            .replace(",", "")
            .replace("\u2212", "-")
        )
        for row in (data.get("service_supply") or {}).get("rows", []):
            for val in (row.get("value_then"), row.get("value_now")):
                if val is not None:
                    assert f"{val}" in supply_readme, (
                        f"supply row {row['agency']} value {val} not in the "
                        "supply derivation"
                    )
            if row.get("pct_change") is not None:
                assert f"{row['pct_change']}" in supply_readme, (
                    f"supply row {row['agency']} pct {row['pct_change']} not "
                    "in the supply derivation"
                )


def test_frozen_sent_email_is_byte_exact():
    """The record of what was actually emailed to Councillor Sample on
    2026-08-25 must never change. It was extracted byte-exact from commit
    b296ac1 ("email sent to Councillor Sample 2026-08-25 10:13") into
    docs/runs/sent-20260825-reid.txt after the regenerated draft was
    mistaken for the send record. Any edit to the frozen file — even one
    character — fails here, and the sha256 must match the pinned value."""
    import hashlib

    sent = _ROOT / "docs" / "runs" / "sent-20260825-reid.txt"
    assert sent.exists(), "frozen sent-text artifact is missing"
    data = sent.read_bytes()
    assert hashlib.sha256(data).hexdigest() == (
        "7f62eb48cb2075d5511ba143b4d76a62fee0e7c1c8b9009144da2957d083653e"
    ), "frozen sent text was modified — restore it from commit b296ac1"
    # Spot-check the sent-only anchors: the pre-Sept-7 reliability window
    # ("9 days", "866 of 28,079", "3.1%") is what Reid received; the
    # regenerated draft says 19 days / 437 / 0.6%.
    text = data.decode("utf-8")
    assert "866 of 28,079 verifiable trips" in text
    assert "9 days of sampling" in text
    assert "437 of 73,980" not in text, (
        "frozen sent text contains post-send numbers — it was overwritten"
    )
